[package]
name = "keyring"
version = "0.1.0"
authors = ["PrideTheDaemon <louis.prudhomme@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.3"
sha2 = "0.9.5"
rust-argon2 = "0.8"
block-modes = "0.8.1"
aes = "0.7.4"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde_json = "1.0.32"
serde_derive = "1.0.80"
serde = "1.0.80"